---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: VBox

platforms:
  - name: instance
    box: centos/7
    memory: 512
    cpus: 1

provisioner:
  name: ansible
  log: true
  options:
    become: true

verifier:
  name: ansible
